#!/bin/bash
###############################################################################
# colors
# Author: John Deng <john.deng@outlook.com>
###############################################################################
export COLOR_PREFIX="\e"
export ECHO_E="echo -e"
if [ "$OS" == "Darwin" ]; then
    export COLOR_PREFIX="\033"
fi

export DARKRED="\033[1;31m"
export RED="\033[3;31m"
export DARKGREEN="\033[1;32m"
export GREEN="\033[3;32m"
export DARKYELLOW="\033[1;33m"
export YELLOW="\033[3;33m"
export DARKBLUE="\033[1;34m"
export BLUE="\033[3;34m"
export DARKPURPLE="\033[1;35m"
export PURPLE="\033[3;35m"
export DARKTEAL="\033[1;36m"
export TEAL="\033[3;36m"
export DARKGRAY="\033[1;90m"
export GRAY="\033[3;37m"
export ENDCOLOR="\033[3;0m"
export CANYON=${TEAL}

export E_DARKRED="${COLOR_PREFIX}[1;31m"
export E_RED="${COLOR_PREFIX}[3;31m"
export E_DARKGREEN="${COLOR_PREFIX}[1;32m"
export E_GREEN="${COLOR_PREFIX}[3;32m"
export E_DARKYELLOW="${COLOR_PREFIX}[1;33m"
export E_YELLOW="${COLOR_PREFIX}[3;33m"
export E_DARKBLUE="${COLOR_PREFIX}[1;34m"
export E_BLUE="${COLOR_PREFIX}[3;34m"
export E_DARKPURPLE="${COLOR_PREFIX}[1;35m"
export E_PURPLE="${COLOR_PREFIX}[3;35m"
export E_DARKTEAL="${COLOR_PREFIX}[1;36m"
export E_TEAL="${COLOR_PREFIX}[3;36m"
export E_ENDCOLOR="${COLOR_PREFIX}[3;0m"
###############################################################################